[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"
startCommand = "npm start"

[deploy]
startCommand = "PORT=8080 npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
