[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"
startCommand = "npm start"

[deploy]
startCommand = "node start.mjs"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
